var appConstants = {
  NEW_MONTH: 'NEW_MONTH',
  FIND_MONTH: 'FIND_MONTH',
  SELECTED_DAY: 'SELECTED_DAY',
  ADD_EVENTS: 'ADD_EVENTS',
  DELETE_EVENTS: 'DELETE_EVENTS',
  ADD_TODO: 'ADD_TODO',
  DELETE_TODO: 'DELETE_TODO',
  TODO_STATUS: 'TODO_STATUS',
  SIGN_UP: 'SIGN_UP'
};

module.exports = appConstants;
